### ISSUE TITLE
norad v1

### ISSUE THREAD

**Issue by chrissimpkins** [linebender/norad#195]
[List is being developed, this is not complete]

Collection of issues to reach v1 release status

- [x] Verify we have all validators from ufoLib on board. Component circular reference checking (from #31)
- [x] Enforce use of name Strings without control characters (from #31, tracker https://github.com/linebender/norad/issues/191)
- [x] More complete user name to filename conversion (from #31, tracker #85)
- [x] Better error reporting 
    - [x] https://github.com/linebender/norad/issues/137
- [ ] review / stabilize the serialization format
- [ ] https://github.com/linebender/norad/issues/194
- [x] Review/expand/clarify source documentation and add the [docs.rs doc link](https://docs.rs/norad/0.6.0/norad/) to repo README (https://github.com/linebender/norad/pull/197)
- [x] Update code to take advantage of newer plist crate (https://github.com/linebender/norad/issues/145)
- [x] Check we prevent downgrades (https://github.com/linebender/norad/issues/25)

Feel free to edit the list in this post.

**Comment by madig** [comment]
@cmyr you wrote on Zulip:

> So the main question is, "what decisions are we unsure of?". One I can think of is the big FontInfo struct, which we might prefer to have be a dict (for instance)

what other things can you think of? My other idea was custom plist ser/de code to drop the slow xml-rs dependency, or maybe we want this upstream?

**Comment by chrissimpkins** [comment]
I started source documentation updates in https://github.com/linebender/norad/pull/197

**Comment by madig** [comment]
Opinions on #202 and #203?

**Comment by madig** [comment]
I want to review our error architecture. Articles I need to ruminate about:

- https://www.unwoundstack.com/blog/rust-error-handling.html
- https://www.lpalmieri.com/posts/error-handling-rust/
- https://kazlauskas.me/entries/errors

**Comment by madig** [comment]
Closing this after closing #31. There's grand stuff left to do, but no manpower to do it right now. Let's use https://github.com/linebender/norad/milestone/2 to track progress to a 1.0.
